name: Build and push to build branch.

on:
  push:
    branches: [trunk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: trunk

      - name: Setup
        uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trim the repo down to just the theme
        run: |
          rm -rf source/wp-content/themes/wporg-main-2022/node_modules
          mv extra/translation-strings.php source/wp-content/themes/wporg-main-2022/extra/translation-strings.php
          mv source/wp-content/themes/wporg-main-2022 $RUNNER_TEMP
          git rm -rfq .
          rm -rf *
          mv $RUNNER_TEMP/wporg-main-2022/* .

      - name: Add all the theme files
        run: |
          git add * --force

      - name: Append build number to version
        run: |
          current_version=$(grep -oP 'Version: \K[0-9]+\.[0-9]+\.[0-9]+' style.css)
          new_version="${current_version}-${GITHUB_SHA::7}"
          sed -i "s/Version: $current_version/Version: $new_version/" style.css

      - name: Commit and push
        uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba # 1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          force: true
          message: 'Build: ${{ github.sha }}'
